name: GitHub Actions Build and Deploy Demo
on:
    push:
        branches:
            - dev
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: dev
                  token: ${{ secrets.ACTION_TOKEN }}
                  fetch-depth: 0

            # 生成静态文件
            - name: Build
              run: npm install && npm run docs:build

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.2.5
              with:
                token: ${{ secrets.ACTION_TOKEN }}
                BRANCH: master
                folder: docs/.vuepress/dist
            #   env:
            #       ACCESS_TOKEN: ${{ secrets.ACTION_TOKEN }}
            #       BASE_BRANCH: dev
            #       branch: master
            #       folder: docs/.vuepress/dist
            #       BUILD_SCRIPT: npm install && npm run docs:build
