name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci # 相当于npm install
    - run: npm run docs:build

    #发布到mybells.github.io/master
    - name: Deploy yuxiaolei1989.github.io/master
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: yuxiaolei1989/yuxiaolei1989.github.io
        BRANCH: master
        FOLDER: docs/.vuepress/dist        
        SSH_PRIVATE_KEY: ${{ secrets.ACTION_TOKEN }}
