name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci # 相当于npm install
    - run: npm run docs:build

    #发布到mybells.github.io/master
    - name: Deploy yuxiaolei1989.github.io/master
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: master
        build_dir: docs/.vuepress/dist
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
