name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
          fetch-depth: 0

      # 生成静态文件
      - name: Build
        run: npm install && npm run docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          branch: master
          folder: docs/.vuepress/dist
          repositoryName: AllenYu0118/allenyu0118.github.io
